image:
  repository: lscr.io/linuxserver/tautulli
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
  pullPolicy: Always

volumes:
  config:
    source: "/mnt/data/tautulli/config"
    dest: "/config"

environment:
  - name: PUID
    value: "121"
  - name: "PGID"
    value: "125"
  - name: TZ
    value: Africa/Johannaesburg

ports:
  http:
    target: 8181
    protocol: TCP

ingress:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: tautulli.arendse.nom.za
      tls: true
      path: /
      service:
        name: http
