---
apiVersion: v1
kind: List
metadata:
  name: app-inventory
items:
  - apiVersion: helm.toolkit.fluxcd.io/v2alpha1
    kind: HelmRelease
    metadata:
      name: echo
      namespace: apps
    spec:
      releaseName: echo
      chart:
        spec:
          chart: ./applications/echo
          source:
            type: HelmRepository
            name: in-repo-chart-server
      values:
        - ./applications/echo/values.yaml
  - apiVersion: helm.toolkit.fluxcd.io/v2alpha1
    kind: HelmRelease
    metadata:
      name: cert-manager
      namespace: cert-manager
    spec:
      releaseName: cert-manager
      chart:
        spec:
          chart: cert-manager
          source:
            type: HelmRepository
            url: https://charts.jetstack.io
      values:
        - ./applications/cert-manager/values.yaml
  - apiVersion: helm.toolkit.fluxcd.io/v2alpha1
    kind: HelmRelease
    metadata:
      name: cilium
      namespace: apps
    spec:
      releaseName: cilium
      chart:
        spec:
          chart: cilium
          source:
            type: HelmRepository
            name: TODO/repoURL
            url: TODO/chart
      values:
        - ./applications/cilium/values.yaml
  - apiVersion: helm.toolkit.fluxcd.io/v2alpha1
    kind: HelmRelease
    metadata:
      name: longhorn
      namespace: apps
    spec:
      releaseName: longhorn
      chart:
        spec:
          chart: longhorn
          source:
            type: HelmRepository
            name: TODO/repoURL
            url: TODO/chart
      values:
        - ./applications/longhorn/values.yaml
  - apiVersion: helm.toolkit.fluxcd.io/v2alpha1
    kind: HelmRelease
    metadata:
      name: traefik
      namespace: apps
    spec:
      releaseName: traefik
      chart:
        spec:
          chart: traefik
          source:
            type: HelmRepository
            name: TODO/repoURL
            url: TODO/chart
      values:
        - ./applications/traefik/values.yaml
  - apiVersion: helm.toolkit.fluxcd.io/v2alpha1
    kind: HelmRelease
    metadata:
      name: vertical-pod-autoscaler
      namespace: apps
    spec:
      releaseName: vertical-pod-autoscaler
      chart:
        spec:
          chart: vertical-pod-autoscaler
          source:
            type: HelmRepository
            name: TODO/repoURL
            url: TODO/chart
      values:
        - ./applications/vertical-pod-autoscaler/values.yaml
  - apiVersion: apps/v1
    kind: Application
    metadata:
      name: pihole
      namespace: apps
    spec:
      source:
        repoURL: ./applications/pihole
        path: .
  - apiVersion: apps/v1
    kind: Application
    metadata:
      name: home-assistant
      namespace: apps
    spec:
      source:
        repoURL: ./applications/home-assistant
        path: .
  - apiVersion: apps/v1
    kind: Application
    metadata:
      name: mongo
      namespace: apps
    spec:
      source:
        repoURL: ./applications/mongo
        path: .
  - apiVersion: apps/v1
    kind: Application
    metadata:
      name: unifi
      namespace: apps
    spec:
      source:
        repoURL: ./applications/unifi
        path: .
