apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: monitoring-auth
  namespace: monitoring
spec:
  basicAuth:
    secret: grafana-basic-auth
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-basic-auth
  namespace: monitoring
type: Opaque
# To be populated manually.
# Use: echo -n "user:$(openssl passwd -apr1 password)" | base64
data:
  users: ""
