# Zitadel OIDC application credentials, generated by Zitadel when each app is
# created. Copy these into the matching externally-managed Kubernetes Secrets
# (e.g. `oauth2-proxy-zitadel`) — they are NOT written to Git, only to the
# Terraform state (Backblaze S3 backend).
#
# Read a single secret with, e.g.:
#   terraform output -json zitadel_oidc_client_ids     | jq -r .oauth2_proxy
#   terraform output -json zitadel_oidc_client_secrets | jq -r .oauth2_proxy

output "zitadel_oidc_client_ids" {
  description = "Generated OIDC client_id per app, keyed by local.oidc_apps key."
  value       = { for k, a in zitadel_application_oidc.app : k => a.client_id }
  sensitive   = true
}

output "zitadel_oidc_client_secrets" {
  description = "Generated OIDC client_secret per app, keyed by local.oidc_apps key."
  value       = { for k, a in zitadel_application_oidc.app : k => a.client_secret }
  sensitive   = true
}

output "zitadel_org_id" {
  description = "ID of the existing organization the homelab project lives in."
  value       = var.zitadel_org_id
}

output "zitadel_project_id" {
  description = "ID of the homelab project."
  value       = zitadel_project.homelab.id
}
