# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# HTTP Configuration for reverse proxy
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16

template:
  - sensor:
      - name: "Electricity Grid Consumption"
        unique_id: electricity_grid_consumption
        state: "{{ states('sensor.electricity_meter_today') }}"
        availability: >
          {{ is_number(states('sensor.electricity_meter_today')) }}
        unit_of_measurement: "kWh"
        device_class: energy
        state_class: total_increasing

      - name: "Gas Consumption"
        unique_id: gas_consumption
        state: "{{ states('sensor.gas_meter_today') }}"
        availability: >
          {{ is_number(states('sensor.gas_meter_today')) }}
        unit_of_measurement: "kWh"
        device_class: gas
        state_class: total_increasing
